packages:
  - '**'
allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': false
  cypress: false
  esbuild: false
  'prisma': true
  sharp: false
autoInstallPeers: true
ignoredBuiltDependencies:
  - cypress
  - esbuild
  - sharp
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
