autoInstallPeers: true
packages:
  - '**'
ignoredBuiltDependencies:
  - cypress
  - esbuild
  - sharp
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': true
  'prisma': false